//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dfg/Desktop/j2oc/j2ObjcCompoent/J2OCCOmpoent/java/src/Othello/Engine/CommandInterface.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CommandInterface")
#ifdef RESTRICT_CommandInterface
#define INCLUDE_ALL_CommandInterface 0
#else
#define INCLUDE_ALL_CommandInterface 1
#endif
#undef RESTRICT_CommandInterface

#if !defined (JOECommandInterface_) && (INCLUDE_ALL_CommandInterface || defined(INCLUDE_JOECommandInterface))
#define JOECommandInterface_

#define RESTRICT_JavaLangRunnable 1
#define INCLUDE_JavaLangRunnable 1
#include "java/lang/Runnable.h"

@protocol JOECommandInterfaceListener;

@interface JOECommandInterface : NSObject < JavaLangRunnable > {
 @public
  id<JOECommandInterfaceListener> m_Listener_;
}

#pragma mark Public

- (instancetype)init;

- (void)ComputeMoveWithJOECommandInterfaceListener:(id<JOECommandInterfaceListener>)Listener;

- (jboolean)ComputeMoveIsPossible;

- (NSString *)GetLastMove;

- (jint)GetLevel;

- (jint)GetScoreBlack;

- (jint)GetScoreWhite;

- (jint)GetSquareWithInt:(jint)x
                 withInt:(jint)y;

- (jint)GetWhoseTurn;

- (void)InterruptComputation;

- (jboolean)InterruptComputationIsPossible;

- (jboolean)MakeMoveWithInt:(jint)x
                    withInt:(jint)y;

- (jboolean)MakeMoveIsPossibleWithInt:(jint)x
                              withInt:(jint)y;

- (jboolean)MoveIsPossible;

- (void)NewGame;

- (jboolean)NewGameIsPossible;

- (void)run;

- (void)SetLevelWithInt:(jint)level;

- (jboolean)SetLevelIsPossible;

- (void)TakeBack;

- (jboolean)TakeBackIsPossible;

- (void)Undo;

- (jboolean)UndoIsPossible;

@end

J2OBJC_STATIC_INIT(JOECommandInterface)

J2OBJC_FIELD_SETTER(JOECommandInterface, m_Listener_, id<JOECommandInterfaceListener>)

FOUNDATION_EXPORT void JOECommandInterface_init(JOECommandInterface *self);

FOUNDATION_EXPORT JOECommandInterface *new_JOECommandInterface_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JOECommandInterface *create_JOECommandInterface_init(void);

J2OBJC_TYPE_LITERAL_HEADER(JOECommandInterface)

@compatibility_alias OthelloEngineCommandInterface JOECommandInterface;

#endif

#pragma pop_macro("INCLUDE_ALL_CommandInterface")
