//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dfg/Desktop/j2oc/j2ObjcCompoent/J2OCCOmpoent/java/src/Othello/Engine/CommandInterfaceListener.java
//

#include "CommandInterfaceListener.h"
#include "J2ObjC_source.h"

#if !__has_feature(objc_arc)
#error "CommandInterfaceListener must be compiled with ARC (-fobjc-arc)"
#endif

@interface JOECommandInterfaceListener : NSObject

@end

#line 1 "/Users/dfg/Desktop/j2oc/j2ObjcCompoent/J2OCCOmpoent/java/src/Othello/Engine/CommandInterfaceListener.java"


#line 13
@implementation JOECommandInterfaceListener

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(ComputationFinishedWithJOEMove:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "ComputationFinished", "LJOEMove;" };
  static const J2ObjcClassInfo _JOECommandInterfaceListener = { "CommandInterfaceListener", "Othello.Engine", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, -1, -1 };
  return &_JOECommandInterfaceListener;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(JOECommandInterfaceListener)

J2OBJC_NAME_MAPPING(JOECommandInterfaceListener, "Othello.Engine", "JOE")
