//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dfg/Desktop/j2oc/j2ObjcCompoent/J2OCCOmpoent/java/src/Othello/Engine/Engine.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Engine")
#ifdef RESTRICT_Engine
#define INCLUDE_ALL_Engine 0
#else
#define INCLUDE_ALL_Engine 1
#endif
#undef RESTRICT_Engine

#if !defined (JOESquareStackEntry_) && (INCLUDE_ALL_Engine || defined(INCLUDE_JOESquareStackEntry))
#define JOESquareStackEntry_

@interface JOESquareStackEntry : NSObject {
 @public
  jint m_x_;
  jint m_y_;
}

#pragma mark Public

- (instancetype)initPackagePrivate;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(JOESquareStackEntry)

FOUNDATION_EXPORT void JOESquareStackEntry_initPackagePrivate(JOESquareStackEntry *self);

FOUNDATION_EXPORT JOESquareStackEntry *new_JOESquareStackEntry_initPackagePrivate(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JOESquareStackEntry *create_JOESquareStackEntry_initPackagePrivate(void);

J2OBJC_TYPE_LITERAL_HEADER(JOESquareStackEntry)

@compatibility_alias OthelloEngineSquareStackEntry JOESquareStackEntry;

#endif

#if !defined (JOESquareStack_) && (INCLUDE_ALL_Engine || defined(INCLUDE_JOESquareStack))
#define JOESquareStack_

@class JOESquareStackEntry;

@interface JOESquareStack : NSObject

#pragma mark Public

- (instancetype)initPackagePrivateWithInt:(jint)size;

- (JOESquareStackEntry *)Pop;

- (void)PushWithInt:(jint)x
            withInt:(jint)y;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(JOESquareStack)

FOUNDATION_EXPORT void JOESquareStack_initPackagePrivateWithInt_(JOESquareStack *self, jint size);

FOUNDATION_EXPORT JOESquareStack *new_JOESquareStack_initPackagePrivateWithInt_(jint size) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JOESquareStack *create_JOESquareStack_initPackagePrivateWithInt_(jint size);

J2OBJC_TYPE_LITERAL_HEADER(JOESquareStack)

@compatibility_alias OthelloEngineSquareStack JOESquareStack;

#endif

#if !defined (JOEMoveAndValue_) && (INCLUDE_ALL_Engine || defined(INCLUDE_JOEMoveAndValue))
#define JOEMoveAndValue_

@interface JOEMoveAndValue : NSObject {
 @public
  jint m_x_;
  jint m_y_;
  jint m_value_;
}

#pragma mark Public

- (instancetype)initPackagePrivateWithInt:(jint)x
                                  withInt:(jint)y
                                  withInt:(jint)value;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(JOEMoveAndValue)

FOUNDATION_EXPORT void JOEMoveAndValue_initPackagePrivateWithInt_withInt_withInt_(JOEMoveAndValue *self, jint x, jint y, jint value);

FOUNDATION_EXPORT JOEMoveAndValue *new_JOEMoveAndValue_initPackagePrivateWithInt_withInt_withInt_(jint x, jint y, jint value) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JOEMoveAndValue *create_JOEMoveAndValue_initPackagePrivateWithInt_withInt_withInt_(jint x, jint y, jint value);

J2OBJC_TYPE_LITERAL_HEADER(JOEMoveAndValue)

@compatibility_alias OthelloEngineMoveAndValue JOEMoveAndValue;

#endif

#if !defined (JOEEngine_) && (INCLUDE_ALL_Engine || defined(INCLUDE_JOEEngine))
#define JOEEngine_

#define RESTRICT_SuperEngine 1
#define INCLUDE_JOESuperEngine 1
#include "SuperEngine.h"

@class JOEGame;
@class JOEMove;

@interface JOEEngine : JOESuperEngine

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)st;

- (instancetype)initWithInt:(jint)st
                    withInt:(jint)sd;

- (JOEMove *)ComputeMoveWithJOEGame:(JOEGame *)g;

@end

J2OBJC_EMPTY_STATIC_INIT(JOEEngine)

FOUNDATION_EXPORT void JOEEngine_initWithInt_withInt_(JOEEngine *self, jint st, jint sd);

FOUNDATION_EXPORT JOEEngine *new_JOEEngine_initWithInt_withInt_(jint st, jint sd) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JOEEngine *create_JOEEngine_initWithInt_withInt_(jint st, jint sd);

FOUNDATION_EXPORT void JOEEngine_initWithInt_(JOEEngine *self, jint st);

FOUNDATION_EXPORT JOEEngine *new_JOEEngine_initWithInt_(jint st) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JOEEngine *create_JOEEngine_initWithInt_(jint st);

FOUNDATION_EXPORT void JOEEngine_init(JOEEngine *self);

FOUNDATION_EXPORT JOEEngine *new_JOEEngine_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JOEEngine *create_JOEEngine_init(void);

J2OBJC_TYPE_LITERAL_HEADER(JOEEngine)

@compatibility_alias OthelloEngineEngine JOEEngine;

#endif

#pragma pop_macro("INCLUDE_ALL_Engine")
