//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dfg/Desktop/j2oc/j2ObjcCompoent/J2OCCOmpoent/java/src/Othello/Engine/Game.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Game")
#ifdef RESTRICT_Game
#define INCLUDE_ALL_Game 0
#else
#define INCLUDE_ALL_Game 1
#endif
#undef RESTRICT_Game

#if !defined (JOEGame_) && (INCLUDE_ALL_Game || defined(INCLUDE_JOEGame))
#define JOEGame_

@class IOSObjectArray;
@class JOEMove;

@interface JOEGame : NSObject

#pragma mark Public

- (instancetype)init;

- (JOEMove *)GetLastMove;

- (JOEMove *)GetMoveWithInt:(jint)i;

- (jint)GetMoveNumber;

- (jint)GetScoreWithInt:(jint)player;

- (jint)GetSquareWithInt:(jint)x
                 withInt:(jint)y;

- (jint)GetWhoseTurn;

- (jboolean)IdenticalWithJOEGame:(JOEGame *)g;

- (jboolean)MakeMoveWithJOEMove:(JOEMove *)m;

- (jboolean)MoveIsAtAllPossible;

- (jboolean)MoveIsLegalWithJOEMove:(JOEMove *)m;

- (jboolean)MoveIsPossibleWithInt:(jint)player;

- (void)Reset;

- (jboolean)TakeBackMove;

- (IOSObjectArray *)TurnedByLastMove;

@end

J2OBJC_EMPTY_STATIC_INIT(JOEGame)

FOUNDATION_EXPORT void JOEGame_init(JOEGame *self);

FOUNDATION_EXPORT JOEGame *new_JOEGame_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JOEGame *create_JOEGame_init(void);

J2OBJC_TYPE_LITERAL_HEADER(JOEGame)

@compatibility_alias OthelloEngineGame JOEGame;

#endif

#pragma pop_macro("INCLUDE_ALL_Game")
