//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dfg/Desktop/j2oc/j2ObjcCompoent/J2OCCOmpoent/java/src/Othello/Engine/Position.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Position")
#ifdef RESTRICT_Position
#define INCLUDE_ALL_Position 0
#else
#define INCLUDE_ALL_Position 1
#endif
#undef RESTRICT_Position

#if !defined (JOEPosition_) && (INCLUDE_ALL_Position || defined(INCLUDE_JOEPosition))
#define JOEPosition_

@class JOEMove;

@interface JOEPosition : NSObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithJOEPosition:(JOEPosition *)p
                        withJOEMove:(JOEMove *)m;

- (JOEMove *)GetLastMove;

- (jint)GetScoreWithInt:(jint)player;

- (jint)GetSquareWithInt:(jint)x
                 withInt:(jint)y;

- (jboolean)MoveIsAtAllPossible;

- (jboolean)MoveIsLegalWithJOEMove:(JOEMove *)m;

- (jboolean)MoveIsPossibleWithInt:(jint)player;

@end

J2OBJC_EMPTY_STATIC_INIT(JOEPosition)

FOUNDATION_EXPORT void JOEPosition_init(JOEPosition *self);

FOUNDATION_EXPORT JOEPosition *new_JOEPosition_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JOEPosition *create_JOEPosition_init(void);

FOUNDATION_EXPORT void JOEPosition_initWithJOEPosition_withJOEMove_(JOEPosition *self, JOEPosition *p, JOEMove *m);

FOUNDATION_EXPORT JOEPosition *new_JOEPosition_initWithJOEPosition_withJOEMove_(JOEPosition *p, JOEMove *m) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JOEPosition *create_JOEPosition_initWithJOEPosition_withJOEMove_(JOEPosition *p, JOEMove *m);

J2OBJC_TYPE_LITERAL_HEADER(JOEPosition)

@compatibility_alias OthelloEnginePosition JOEPosition;

#endif

#pragma pop_macro("INCLUDE_ALL_Position")
