//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dfg/Desktop/j2oc/j2ObjcCompoent/J2OCCOmpoent/java/src/Othello/Engine/Score.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Score")
#ifdef RESTRICT_Score
#define INCLUDE_ALL_Score 0
#else
#define INCLUDE_ALL_Score 1
#endif
#undef RESTRICT_Score

#if !defined (JOEScore_) && (INCLUDE_ALL_Score || defined(INCLUDE_JOEScore))
#define JOEScore_

@interface JOEScore : NSObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)whitescore
                    withInt:(jint)blackscore;

+ (jint)GetOpponentWithInt:(jint)player;

- (jint)GetScoreWithInt:(jint)player;

- (void)ScoreAddWithInt:(jint)player
                withInt:(jint)amount;

- (void)ScoreCopyWithJOEScore:(JOEScore *)s;

- (void)ScoreSubtractWithInt:(jint)player
                     withInt:(jint)amount;

- (void)SetScoreWithInt:(jint)player
                withInt:(jint)score;

@end

J2OBJC_EMPTY_STATIC_INIT(JOEScore)

inline jint JOEScore_get_NOBODY(void);
#define JOEScore_NOBODY 0
J2OBJC_STATIC_FIELD_CONSTANT(JOEScore, NOBODY, jint)

inline jint JOEScore_get_WHITE(void);
#define JOEScore_WHITE 1
J2OBJC_STATIC_FIELD_CONSTANT(JOEScore, WHITE, jint)

inline jint JOEScore_get_BLACK(void);
#define JOEScore_BLACK 2
J2OBJC_STATIC_FIELD_CONSTANT(JOEScore, BLACK, jint)

FOUNDATION_EXPORT void JOEScore_init(JOEScore *self);

FOUNDATION_EXPORT JOEScore *new_JOEScore_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JOEScore *create_JOEScore_init(void);

FOUNDATION_EXPORT void JOEScore_initWithInt_withInt_(JOEScore *self, jint whitescore, jint blackscore);

FOUNDATION_EXPORT JOEScore *new_JOEScore_initWithInt_withInt_(jint whitescore, jint blackscore) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JOEScore *create_JOEScore_initWithInt_withInt_(jint whitescore, jint blackscore);

FOUNDATION_EXPORT jint JOEScore_GetOpponentWithInt_(jint player);

J2OBJC_TYPE_LITERAL_HEADER(JOEScore)

@compatibility_alias OthelloEngineScore JOEScore;

#endif

#pragma pop_macro("INCLUDE_ALL_Score")
